Fix adds port param for Class A device downlinks.
tago-io/sdk-js pull request #104
Opened 2023-12-13 17:45 UTC by Freddyminu

## What does PR do?

Adds the "port" configuration parameter so that users can use Utils.sendDownlink() to send downlinks to LoRaWAN Class C devices. At the moment the function only adds the downlink param, this isn't enough some networks/devices.

...

## Type of alteration

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

2023-12-13 17:48 UTC, vitorfdl requested changes

2023-12-13 17:48 UTC, vitorfdl commented on src/modules/Utils/sendDownlink.ts
> +    value: String(dn_options.port),
cast the port to string with String() since the sendDownlink doesn't have edge case for port type

2024-06-26 18:42 UTC, vitorfdl approved these changes

2024-06-26 18:54 UTC, felipefdl approved these changes

2024-06-26 18:55 UTC, merged