feat/updating-jsdoc
tago-io/sdk-js pull request #135
Opened 2024-12-17 18:44 UTC by mateuscardosodeveloper

## What does PR do?

Workin In Progress

## Type of alteration

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [x] Documentation update

2025-02-18 17:33 UTC, vitorfdl approved these changes

2025-02-18 17:35 UTC, vitorfdl requested changes

2025-02-18 17:35 UTC, vitorfdl commented on src/common/common.types.ts
> +interface Autenticador {
Portuguese? It should be english

2025-02-18 17:51 UTC, vitorfdl approved these changes

2025-02-28 17:55 UTC, cotrin approved these changes

2025-02-28 17:55 UTC, cotrin commented on src/modules/Resources/entities.types.ts
> +  filter?: Record<string, string | { start: string | null; end: string | null }>;
Record<string, string | number | boolean | { start: string | null; end: string | null }>

2025-03-19 15:06 UTC, merged