Improve the interface of the Actions class
tago-io/sdk-js pull request #98
Opened 2023-07-12 20:40 UTC by mateuscardosodeveloper

## What does PR do?

Updated the interface of the Actions class, with data that had not been mapped before.

...

## Type of alteration

- [ ] Bug fix
- [ ] New feature
- [x] Breaking change
- [ ] Documentation update

2023-08-18 19:28 UTC, RicardoStoklosa approved these changes

2023-08-18 19:33 UTC, vitorfdl requested changes

2023-08-18 19:33 UTC, vitorfdl commented on src/modules/Resources/actions.types.ts
> +      script: string | string[];
Why string? Correct for script is GenericID | GenericID[]

2023-08-18 19:33 UTC, vitorfdl commented on src/modules/Resources/actions.types.ts
> +      qos?: number;
QOS doesn't accept any number. It must be 1, 2 or 3

2023-08-18 19:33 UTC, vitorfdl commented on src/modules/Resources/actions.types.ts
> +      tcore_id: string;
GenericID

2023-08-18 19:33 UTC, vitorfdl commented on src/modules/Resources/actions.types.ts
> +      fallback_token?: string | null | undefined;
why null | undefined ?

2023-08-18 19:33 UTC, vitorfdl commented on src/modules/Resources/actions.types.ts
> +  description?: string | null | undefined;
why null | undefined ?

2023-08-18 19:33 UTC, vitorfdl commented on src/modules/Resources/actions.types.ts
>        headers: {};
Empty JSON?

2023-09-18 11:57 UTC, RicardoStoklosa requested changes

2023-09-18 11:57 UTC, RicardoStoklosa commented on src/modules/Resources/actions.types.ts
> +      qos?: 1 | 2 | 3;
```suggestion
      qos?: 0 | 1 | 2;
```

2023-09-18 11:57 UTC, RicardoStoklosa commented on src/modules/Resources/actions.types.ts
> +      headers: Record<string, string>;
```suggestion
      headers?: Record<string, string>;
```

2026-06-15 16:55 UTC, closed without merging